version: '3.8'

services:
docsanthropic2api:
  image: yxmiler/docsanthropic2api:latest
  container_name: docsanthropic2api
  ports:
    - "3000:3000"
  environment:
    - API_KEY=sk-123456
    - PORT=3000
    - INKEEP_AUTH_TOKEN=your_INKEEP_AUTH_TOKEN
  restart: unless-stopped
